#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

find /home/bug/Storage/media/tv -name "*.mkv" | while read f
do ffmpeg -i "$f" -c copy -y -flags +global_header -acodec aac -strict -2 -b:a $
done;

find /home/bug/Storage/media/ -name "*.mkv" | while read f
do rm "$f";
done;

logger "convertdelete cron Done"
